config/routes.rb
MastermindApp::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  get '/' => 'static_pages#home', as: 'root'
  get '/rules' => 'static_pages#rules', as: 'rules'
  get '/play' => 'games#new_game', as: 'new_game'
  post '/play' => 'games#play', as: 'play'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
require 'page_interface'
require 'mastermind'

class GamesController < ApplicationController
  
  def new_game
  end
 
  def play
    code = params[:code][:code]
  
    io = IO.new(code)
    if(Mastermind::Validator.new(io.formatted_input, 4, %w{R G O Y B P}).valid?)
      game_text = Mastermind::GameText.new
      io = IO.new(code)
      @result=Game.new(game_text, io).play_game(io.formatted_input)
      @index = 0
      @display_text = io.messages
    else
      flash.now[:error] = "Invalid code"
      render 'new_game'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def rules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  class Terminal
    def initialize input
      @input = input
      @display_text = "HI"
    end

    def display(message)
    end
    
    def formatted_input
      @input.upcase.split(%r{\s*})
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/new_game.html.erb
<div class="center hero-unit">
  <h1>Welcome to Mastermind</h1>
  <%= Mastermind::GameText.new.message(:prompt) %><br />

  <% colors = ["red", "orange", "yellow", "green", "blue", "purple"] %>
  
  <div class="button_row">
  <% colors.each do |color| %>
    <button id=<%=color%>></button>  
  <% end %>
  </div> 
  
  <div class="row">
    <%= form_for :code do |f| %>
    <%= f.text_field :code%><br />
    <%= f.submit "Play", class: "btn btn-large btn-primary" %>
  <% end %>
  </div>
  
  
</div>

app/views/games/play.html.erb
<% #game_text = Mastermind:: GameText.new %>
<h1>Welcome to Mastermind</h1>
    <p>
      <% if @display_text %>
          <ul id="messages">
             <% @display_text.each do |message| %>
             <li><% JSON.parse(message).join.each_char do |letter|%>
                  
                  <div class="color_box <%=letter%>" style="display: inline-block;">&nbsp;</div>    
                 <% end %> </li> 
              <% end %>
          <li><%= @result %></li>
          </ul>
             <br><%= link_to "Next Guess", '#' , class: "btn btn-large btn-primary" %></br>
      <% end %>
    </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MastermindApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top nav navbar-inverse">
    <div class="navbar-inner">
      <div class="containter">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Play", root_path %></li>
          <li><%= link_to "Game Rules", rules_path %></li>
        </ul>
      </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class= "alert alert-<%=key%>"><%=value%></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Mastermind Game</h1>
  <h2>
    A simple mastermind game with an AI solver. 
  </h2>

  <%= link_to "Play Here!", new_game_path , class: "btn btn-large btn-primary" %>  

</div>

app/views/static_pages/rules.html.erb
<h1>How to Play</h1>
  <p>
    Mastermind is a color guessing game. Player 1 chooses a 4 color code (colors
    can repeat) from 6 possible colors. Player 2 then tries to guess the code.
    After each guess, the guessing player is told how many correct positions
    (correct color in the correct place) there are and how many correct colors
    (correct color in the incorrect place) there are. The guessing player gets a
    maximum of 10 tries. 
  </p>
</h1>